package de.michel.projecteuler.problems0001_0050.problem0002;

/**
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * <pre>1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...</pre>
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * 
 * @author micmeyer
 */
public class Problem0002
{
    public static void main(String[] args)
    {
        int a = 1;
        int b = 2;
        int c;
        int sum = 2;
        
        while ((c = a + b) < 4000000)
        {
            if (c % 2 == 0)
            {
                sum += c;
            }
            a = b;
            b = c;
        }
        
        System.out.println(sum);
    }
}
